# .github/workflows/kudos.yml
name: Kudos for Code
defaults:
  run:
    working-directory: .
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  kudos:
    name: Supporting your open source team.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          image: ghcr.io/sangheestyle/ort:latest
          run: cache-dependencies, analyzer, reporter, upload-results
      - name: Read ORT result
        run: |
          ls $HOME/.ort/ort-results
          cat $HOME/.ort/ort-results/analyzer-result.json
