# .github/workflows/kudos.yml
name: Kudos for Code
defaults:
  run:
    working-directory: .
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  kudos:
    name: Supporting your open source team.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          image: ghcr.io/sangheestyle/ort:latest
          run: cache-dependencies, analyzer, upload-results
      - name: Generate Kudos
        run: |
          curl -LO https://github.com/LoremLabs/kudos-for-code/releases/download/v0.0.3/kudos-for-code-v0.0.3-linux-amd64.tar.gz
          tar -zxvf kudos-for-code-v0.0.3-linux-amd64.tar.gz
          ./kudos-for-code projectName $HOME/.ort/ort-results/analyzer-result.json
